###
# Town

###
# Create town

POST http://localhost:5000/town HTTP/1.1
Content-Type: application/json

{
    "name": "xDD",
    "recruiting": true
}


###
# Change town name

PUT http://localhost:5000/town/607ab1e8236e672234117aa3/changeName HTTP/1.1
Content-Type: application/json

{
    "name": "Piła"
}

###
# Change town recruiting status

PUT http://localhost:5000/town/607ab1e8236e672234117aa3/changeStatus HTTP/1.1
Content-Type: application/json

{
    "recruiting": false
}

###
# Add CV in Postman to load the file

###
# Remove CV

PUT http://localhost:5000/town/607ab1e8236e672234117aa3/removeCv HTTP/1.1
Content-Type: application/json

{
    "id": "607b71c8446e7051e0cd81ad"
}