###
# Town

###
# Create town

POST http://localhost:5000/town HTTP/1.1
Content-Type: application/json

{
    "name": "xDD",
    "recruiting": true
}

###
# Get all towns

GET http://localhost:5000/town HTTP/1.1


###
# Get single town info

GET http://localhost:5000/town/607ac25dad2d8e4684dd452f HTTP/1.1


###
# Change town name

PUT http://localhost:5000/town/607ab1e8236e672234117aa3/changeName HTTP/1.1
Content-Type: application/json

{
    "name": "Piła"
}

###
# Change town recruiting status

PUT http://localhost:5000/town/607ab1e8236e672234117aa3/changeStatus HTTP/1.1
Content-Type: application/json

{
    "recruiting": false
}

###
# Add CV in Postman to load the file

###
# Remove CV

PUT http://localhost:5000/town/607ab1e8236e672234117aa3/removeCv HTTP/1.1
Content-Type: application/json

{
    "id": "607c03cbafc1e411b4c7cdb8"
}

### Store

###
# Create store

POST http://localhost:5000/town/607ab1e8236e672234117aa3/store HTTP/1.1
Content-Type: application/json

{
    "name": "Górne",
    "description": "Sample description",
    "address": {
        "street": "Górne street"
    },
    "contact": "(+48) 123321123",
    "openHours": {
        "monday": "7:00 - 14:00",
        "tuesday": "7:00 - 14:00",
        "wednesday": "7:00 - 14:00",
        "thursday": "7:00 - 14:00",
        "friday": "7:00 - 14:00",
        "saturday": "7:00 - 14:00",
        "sunday": "7:00 - 14:00"
    },
    "suppDay": "Monday",
    "price": {
        "monday": 20,
        "tuesday": 50,
        "wednesday": 10,
        "thursday": 15,
        "friday": 2,
        "saturday": 100,
        "sunday": 8000
    }
}

### add/edit gallery
# Postman to send files

###
# Get store information

GET http://localhost:5000/town/607ab1e8236e672234117aa3/store/607c14735158a518c8edab6e HTTP/1.1


###
# Change store information

PUT http://localhost:5000/town/607ab1e8236e672234117aa3/store/607c14735158a518c8edab6e HTTP/1.1
Content-Type: application/json

{
    "name": "wtf",
    "description": "Sample description",
    "address": {
        "street": "srurne kurwa street"
    },
    "contact": "(+48) 123321123",
    "openHours": {
        "monday": "7:00 - 14:00",
        "tuesday": "7:00 - 14:00",
        "wednesday": "7:00 - 14:00",
        "thursday": "7:00 - 14:00",
        "friday": "7:00 - 14:00",
        "saturday": "7:00 - 14:00",
        "sunday": "7:00 - 14:00"
    },
    "suppDay": "Monday",
    "price": {
        "monday": 20,
        "tuesday": 50,
        "wednesday": 10,
        "thursday": 15,
        "friday": 2,
        "saturday": 100,
        "sunday": 8000
    }
}