###
# Town

###
# Create town

POST http://localhost:5000/town HTTP/1.1
Content-Type: application/json

{
    "name": "xDD",
    "recruiting": true
}

###
# Get all towns

GET http://localhost:5000/town HTTP/1.1


###
# Get single town info

GET http://localhost:5000/town/607ac25dad2d8e4684dd452f HTTP/1.1


###
# Change town name

PUT http://localhost:5000/town/607ab1e8236e672234117aa3/changeName HTTP/1.1
Content-Type: application/json

{
    "name": "Piła"
}

###
# Change town recruiting status

PUT http://localhost:5000/town/607ab1e8236e672234117aa3/changeStatus HTTP/1.1
Content-Type: application/json

{
    "recruiting": false
}

###
# Add CV in Postman to load the file

###
# Remove CV

PUT http://localhost:5000/town/607ab1e8236e672234117aa3/removeCv HTTP/1.1
Content-Type: application/json

{
    "id": "607c03cbafc1e411b4c7cdb8"
}